### ISSUE TITLE
Need wordpress.org assets

### ISSUE THREAD

**Issue by aaronware** [linchpin/courier-notices#98]
Regular: banner-772×250.(jpg|png)
Retina: banner-1544×500.(jpg|png)

icon-128×128.(jpg|png)
icon-256×256.(jpg|png)
icon.svg

**Comment by erroneous5000** [comment]
@aaronware folder on dropbox has all the assets. Let me know what you think of the banner. The only thing that's missing are any screenshots of the admin or frontend we want to include but I imagine those would need to come once styling is finalized.
[plugin-directory-assets](https://www.dropbox.com/sh/rc8zt49v9ziwjhp/AABoa7Q9EHWaK3FqsQPBrYhPa?dl=0)

**Comment by aaronware** [comment]
Thanks @erroneous5000 . Yep once the css is all set in the admin we'll take some screenshots and some usage videos for the site

**Comment by aaronware** [comment]
This is all set in 1.3.0 I added a few screenshots for users how the plugin works
